### ISSUE TITLE
Update node version to 16

### ISSUE THREAD

**Issue by srisudarsan** [PaloAltoNetworks/prisma-cloud-scan#19]
With node12 reaching its end of life,gihub has started the deprecation for actions running on node v12. 
as a result, we are getting the below warnings in CI runs
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: PaloAltoNetworks/prisma-cloud-scan`

We have to upgrade the node version to 16 to support this change

**Comment by wfg** [comment]
Fixed in #23
