### ISSUE TITLE
Support for --project parameter

### ISSUE THREAD

**Issue by mikocot** [PaloAltoNetworks/prisma-cloud-scan#27]
### Is your feature request related to a problem?

Yes, we need to specify a project when running scans in the pipeline to apply particular configuration specific to it and have reports available there.

### Describe the solution you'd like

Add an action parameter to action to specify the project in addition to the current ones.

### Describe alternatives you've considered

The only alternative is to not use the action and wrap the twistlock cli command ourselves.

### Additional context

As specified in twistlock cli specs:

> Projects
> When users from a tenant project run twistcli, they must set the [--project](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/tools/twistcli_scan_images#) option to specify the proper context for the command.
> [twistcli images scan --project "<project_name>"](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/tools/twistcli_scan_images#)

It should be a very easy part to add, while also a valuable feature for those working with multiple projects within their prisma cloud console.

**Comment by mikocot** [comment]
I've addressed this issue in my PR: https://github.com/PaloAltoNetworks/prisma-cloud-scan/pull/28

**Comment by jirikopecky** [comment]
Any update on this? Would it be possible to merge #28 ?
