### ISSUE TITLE
Update action runtime to node20

### ISSUE THREAD

**Issue by jirikopecky** [PaloAltoNetworks/prisma-cloud-scan#49]
### Is your feature request related to a problem?

Node16 reached end-of-life and [GitHub deprecated the `node16` runtime for actions](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Using any action that still runs on `node16` emits warning to the workflow log.

### Describe the solution you'd like

Please update the action to use `node20` runtime.

**Comment by mikocot** [comment]
would anyone mind looking into the PR?

**Comment by jirikopecky** [comment]
Fixed with #50
