### ISSUE TITLE
Error: Failed formatting SARIF: Unknown severity: unassigned

### ISSUE THREAD

**Issue by mikocot** [PaloAltoNetworks/prisma-cloud-scan#55]
## Describe the bug
When scan result contains some vulnerabilities with severity level set to `unassigned` the action fails to parse the sarif file.

The action seems to already handle some of the levels i.e. `unknown', but not this one. Not sure if that's new but they started showing up for our images and caused passing scans to fail with:

> Error: Failed formatting SARIF: Unknown severity: unassigned

## Expected behavior

- parse sarif files without error
- consider unassigned level as 'none'

## Current behavior

> Error: Failed formatting SARIF: Unknown severity: unassigned
action fails

## Possible solution

add support for the unassigned level

## Steps to reproduce

1. scan any image that produces unassigned level vulnerabilities

## Screenshots
![image](https://github.com/PaloAltoNetworks/prisma-cloud-scan/assets/9884950/fdd9c824-32d1-44c2-891e-e76e3899edb9)

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by mikocot** [comment]
the solution is now ready in the PR #56 just waiting for the contributors to merge. It's also the version now tested and used in our CICD

**Comment by giulianozor** [comment]
Hello,
We have the same issue. Is there any timeframe for the Parks merge ?
Thanks
