### ISSUE TITLE
Feature request: accept access key and secret access key instead of user/pass

### ISSUE THREAD

**Issue by deeno35** [PaloAltoNetworks/prisma-cloud-scan#57]
### Is your feature request related to a problem?

As a user I would like to use a service account to execute Prisma scans

### Describe the solution you'd like

being able to pass in the access key id and secret access key instead of user and password would allow this

### Describe alternatives you've considered

Open to suggestions

### Additional context

For logging purposes, it is not great for automated CI scans to be run as individual users.  It would be better to use the native service account.  For the time being, the workaround has been to create a dummy account in prisma and use that.

**Comment by sgordon46** [comment]
@deeno35 a Service Account will work for this scan already.

https://docs.prismacloud.io/en/enterprise-edition/content-collections/administration/add-service-account-prisma-cloud
